#!/usr/bin/bash

/home/cognusboi/workspace/programming/python/metalearn/scripts/bin/python /home/cognusboi/workspace/programming/python/metalearn/scripts/src/main.py /home/cognusboi/workspace/programming/c++/cc/problems.db
