#!/bin/sh

case $1 in
	-s|--stop)
		killall takeabreak
		break
		;;
esac

stretch() {
	COUNT=0
	DUR=20000
	while true; do
		sleep 20m
		COUNT=$((COUNT+1))
		ffplay -nodisp -hide_banner -volume 20 -loglevel quiet -autoexit $SCRIPTS/sound.oga &
		if [[ COUNT -gt 3 ]];then
			COUNT=0
			notify-send "bsdk pani peele" -t $DUR
			sleep 1m
		else 
			notify-send "Stretch for 20 seconds" -t $DUR
		fi
	done
}

if [[ $(pgrep -c -x takeabreak) -le 1 ]]; then
	stretch &
fi
