#!/bin/sh

gum style \
	--border normal \
	--margin "1" \
	--padding "1" \
	"Wi-Fi Selection tool"

echo "Please select a network:"
wifi=$(nmcli --fields SSID --terse --color no device wifi list | gum choose)

password=$(gum input --password --placeholder="Wifi password")
if [[ -z "$password" ]]; then
	nmcli device wifi connect $wifi
else	
	nmcli device wifi connect $wifi password $password
fi
