require('custom.options')
require('custom.plugins')
require('custom.telescope')
require('custom.treesitter')
require('custom.keymaps')
require('custom.nvim-cmp')
require('custom.toggleterm')
require('custom.lsp')
