require('plugins')
require('options')
require('mappings')
require('plugins/nvim-lspconfig')
require('plugins/nvim-cmp')
require('plugins/treesitter')
require('plugins/lualine')
require('plugins/nvim-tree')
